import os
import sys
import json
import requests
import pulp
import math
from google import genai
from google.genai import types
from ddgs import DDGS

# combined functions
from fpl_funcs import (
    estimate_xmins,
    calculate_tier1_translation_factor,
    get_gameweek_state,
    get_base_ev,
    get_macro_ev,
    get_ensemble_ev,
    normalize_player,
    calculate_dynamic_bench_discount,
    evaluate_chip_thresholds
)
from fpl_odds_engine import get_market_adjustments
from fpl_mpo_engine import solve_multi_period_model

# 1. Environment & Pre-Flight Check
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")
FPL_TEAM_ID = os.environ.get("FPL_TEAM_ID")
WORKFLOW_INPUT = os.environ.get("MANUAL_TRIGGER", "auto")
XMINS_INPUT = os.environ.get("XMINS_INPUT", "")
ACTIVE_CHIP = os.environ.get("ACTIVE_CHIP", "NONE").upper() 
RISK_POSTURE = os.environ.get("RISK_POSTURE", "NEUTRAL")
STATE_FILE_PATH = "fpl_state.json"

UEFA_TEAMS = {"MCI", "ARS", "LIV", "AVL", "MUN", "NEW", "CHE", "TOT", "SUN"}

if not all([GEMINI_API_KEY, DISCORD_WEBHOOK_URL, FPL_TEAM_ID]):
    print("CRITICAL ERROR: Missing GitHub Secrets (GEMINI_API_KEY, DISCORD_WEBHOOK_URL, or FPL_TEAM_ID).")
    sys.exit(1)

client = genai.Client(api_key=GEMINI_API_KEY)

SYSTEM_INSTRUCTION = """
You are an institutional-grade Quantitative Fantasy Premier League (FPL) Analyst and Tactical Decision Engine. Your purpose is to evaluate squad selections, transfers, captaincy choices, and chip strategies using advanced underlying metrics, pitch geometry, game-state data, and FPL market economics. You must strictly adhere to the following analytical laws.

### CORE DATA INTEGRITY GUARDRAILS
1. STRICT DATA IMMUTABILITY: You must copy player names, team tags, positions, costs, xMins, and EV values EXACTLY as presented in the MATHEMATICALLY LOCKED SQUAD payload. Do NOT alter, overwrite, or assume club affiliations or positions from past historical memory.
2. ACTIVE MARKET ISOLATION: Base all qualitative commentary exclusively on players active within the provided Premier League database. Ignore mentions of non-Premier League players that may appear in external ITK or search feeds.

### CORE ANALYTICAL LAWS & METRIC DEFINITIONS
1. GAME-STATE NORMALISED ATTACKING & BAYESIAN SHRINKAGE
- Bayesian Filter: Expected goals (xG/xAG) for low-minute fringe players are mathematically shrunken toward positional averages to eliminate small-sample-size data explosions.
- Continuous Market Scalar: The system applies a fluid multiplier to xG based on player cost, reflecting the market's inherent pricing of elite finishing ability.
- Accidental Assist Rule: FPL awards assists for deflected passes if there is only one defensive touch inside the box. Prioritize "Raw Crosses into the Penalty Box" alongside xAG.

2. DEFENSIVE CONTRIBUTION (DefCon) & 2026/27 BPS MATHEMATICS
- DefCon Thresholds: Target baseline assets averaging >8.5 CBIT (Clearances, Blocks, Interceptions, Tackles) for defenders, and >10.5 CBIRT (+ Recoveries) for midfielders/forwards.
- BPS Adjustments: Centre-backs earn 1 BPS per 3 CBI actions. Dribblers face no -1 penalty for being tackled. Penalty goals are a flat 12 BPS for all positions.
- Poisson Clean Sheet Probability: Goalkeeper and Defender EV is mathematically derived from an exponential Poisson decay of their team's Expected Goals Against (xGA), strictly gated by 60-minute threshold probability.

3. CHIP STRUCTURE & MULTI-PERIOD TRANSFER TREE ECONOMICS
- 5-Transfer Banking: Evaluate 0-transfer rolls as an appreciating asset building toward a 3-to-5 transfer "mini-wildcard".
- Multi-Period Transfer Trees: Explicitly detail and justify the transfer roadmap generated by the MPO solver across future horizons.
- Point Hit Constraint: Forbidden from recommending a point hit (-4) unless the 4-Gameweek Expected Value (EV) of the incoming player exceeds the outgoing player by >5.5 points, OR if required to field 11 starters.

4. QUALITATIVE OVERRIDES & TIER-1 LEAK VERIFICATION
- 15-Minute Panic Rule: Late leaks affecting >2 decisions within 15 mins of deadline default to the original multi-week EV plan.
- Cup Congestion Law: Apply a 25% xMins penalty to starters with <72 hours turnaround from cup matches. If no turnarounds violate 72 hours, state this concisely.

5. FOREIGN TRANSFERS & TIERED LEAGUE TRANSLATION
- Tiered Translation Coefficients: Apply granular scaling multipliers to expected attacking output (npxG/xAG) based on competition source tiers.
- Returning Player Exception Logic: Assets with stale early Premier League history but recent elite European peaks bypass blunt rookie discounts via intelligent exception overrides.

### OUTPUT FORMAT & AESTHETIC DIRECTIVES
You MUST format your analysis with extreme visual precision for Discord rendering.

SECTION 1: EXECUTIVE SUMMARY & CORE MOVES
- Strategic summary tailored specifically to the run mode (PRE-GW DEADLINE or POST-GW REVIEW).
- Include a monospaced ASCII Pitch Map block inside a markdown text codeblock displaying the starting formation and bench hierarchy.
- Detail Foreign Transfer / Law 7 Audit and Tactical Mitigation Flags.

SECTION 2: QUANTITATIVE TRADE-OFF SUMMARY
- Format strictly as compact, high-density, single-line bullet points per player:
  • **[Player Name]** ([POS] | [TEAM] | £[X.X]m) — **[xMins] xMins** | **[EV] EV** | [DefCon / xGA / Metric Status]

SECTION 3: TRANSFER ECONOMICS & CHIP STATUS
- Capital management, rolling transfer economics, market volatility, and macro chip timeline.
- EXPLICITLY review and explain the MULTI-PERIOD TRANSFER TREE (MPO) roadmap and the ALGORITHMIC CHIP RECOMMENDATIONS provided in the payload.

SECTION 4: SPATIAL, GAME-STATE & MOTIVATION JUSTIFICATION
- Include an ASCII Spatial Overload / Pitch Mismatch Diagram inside a markdown text codeblock.
- Detail Law 1 Game-State Normalization, Law 3 Spatial Mismatches, and Law 2 DefCon BPS math.

SECTION 5: ITK & CONGESTION AUDIT
- ASCII Matrix or structured breakdown covering ITK, Ben Dinnery injuries, and Ben Crellin schedule congestion.

MANDATORY SIGN-OFF: FINAL LOCKED-IN SQUAD SUMMARY
- Conclude with the exact ASCII Box block provided in the payload containing the FINAL LOCKED-IN SQUAD SUMMARY, MULTI-PERIOD TRANSFER TREE, ALGORITHMIC CHIP RECOMMENDATIONS, and the SQUAD HEALTH & VARIANCE REPORT. Wrap this entire block inside a markdown text codeblock.

CRITICAL FORMATTING RULE: Strictly AVOID LaTeX syntax (e.g. $, $$, \\text{}, \\times). Use plain text and standard Markdown formatting exclusively.
"""

# 2. State Persistence & Calibration Engine
def load_state():
    default_state = {
        "buyback_targets": {},
        "last_updated_gw": 0,
        "xmins_overrides": {}, 
        "price_watchlist": {},
        "calibration_weights": {
            "xgi_weight": 0.70,
            "fdr_impact_factor": 0.10,
            "bench_discount": 0.01
        },
        "pending_evaluation": None,
        "performance_history": []
    }
    if os.path.exists(STATE_FILE_PATH):
        try:
            with open(STATE_FILE_PATH, "r") as f:
                saved_state = json.load(f)
                for key, val in default_state.items():
                    if key not in saved_state:
                        saved_state[key] = val
                return saved_state
        except Exception as e:
            print(f"WARNING: Error reading state file: {e}")
    return default_state

def save_state(state):
    try:
        with open(STATE_FILE_PATH, "w") as f:
            json.dump(state, f, indent=4)
        print("STATE ENGINE: Successfully saved updated strategy state to fpl_state.json")
    except Exception as e:
        print(f"ERROR: Failed to save state file: {e}")

def recalibrate_model(state, headers, active_gw):
    pending = state.get("pending_evaluation")
    if not pending:
        return state

    eval_gw = pending.get("gw")
    if active_gw <= eval_gw:
        return state

    try:
        resp = requests.get(f"https://fantasy.premierleague.com/api/entry/{FPL_TEAM_ID}/event/{eval_gw}/picks/", headers=headers)
        if resp.status_code == 200:
            data = resp.json()
            actual_points = data.get("entry_history", {}).get("points", 0)
            projected_xP = pending.get("projected_xP", 0.0)
            residual_error = actual_points - projected_xP

            state["performance_history"].append({
                "gw": eval_gw,
                "projected_xP": round(projected_xP, 2),
                "actual_points": actual_points,
                "residual_error": round(residual_error, 2),
                "captain": pending.get("captain")
            })

            recent_history = state["performance_history"][-6:]
            if len(recent_history) >= 2:
                mean_error = sum(h["residual_error"] for h in recent_history) / len(recent_history)
                weights = state["calibration_weights"]
                learning_rate = 0.02
                if mean_error < -5.0:
                    weights["xgi_weight"] = max(0.50, round(weights["xgi_weight"] - learning_rate, 3))
                elif mean_error > 5.0:
                    weights["xgi_weight"] = min(1.00, round(weights["xgi_weight"] + learning_rate, 3))
            state["pending_evaluation"] = None
    except Exception as e:
        print(f"WARNING: Error during model recalibration: {e}")

    return state

# 3. Live Search Data Fetcher
def get_live_fpl_news():
    news_text = "### LIVE ITK NEWS & SCHEDULE DATA (Automatically Fetched)\n"
    try:
        crellin_results = DDGS().text("Ben Crellin FPL blank double gameweek updates", max_results=3)
        news_text += "--- SCHEDULE CHANGES (Ben Crellin) ---\n"
        for r in crellin_results:
            news_text += f"- {r.get('body', '')}\n"
            
        dinnery_results = DDGS().text("Ben Dinnery FPL injuries team news press conference", max_results=3)
        news_text += "\n--- INJURY UPDATES (Ben Dinnery) ---\n"
        for r in dinnery_results:
            news_text += f"- {r.get('body', '')}\n"
    except Exception as e:
        news_text += f"[Search tool failed to retrieve live data: {e}]\n"
    return news_text

def check_european_congestion_flags(starters, fixtures_data, target_gw):
    flags = []
    for p in starters:
        if p["team"] in UEFA_TEAMS:
            flags.append(f"[FLAG OPTION: European Turnaround Risk detected for {p['name']} ({p['team']}) due to mid-week fixture congestion.]")
    return flags

# 6. Main Data Pipeline & Integration
def get_fpl_data():
    print("Fetching live market odds for tactical alignment...")
    market_data = get_market_adjustments()
    
    headers = {"User-Agent": "FPL-Auto-Script/13.0"}
    state = load_state()
    xmins_overrides = state.get("xmins_overrides", {})
    price_watchlist = state.get("price_watchlist", {})
    
    try:
        bootstrap_resp = requests.get("https://fantasy.premierleague.com/api/bootstrap-static/", headers=headers)
        if bootstrap_resp.status_code != 200:
            print(f"CRITICAL ERROR: FPL API returned status {bootstrap_resp.status_code}. The game is likely updating.")
            sys.exit(1)
        bootstrap_data = bootstrap_resp.json()
    except Exception as e:
        print(f"ERROR fetching bootstrap data: {e}")
        sys.exit(1)

    # Resolve gameweek targets & team mappings
    active_gw, target_gw = get_gameweek_state(bootstrap_data)
    teams = {t["id"]: t["short_name"] for t in bootstrap_data["teams"]}
    element_types = {e["id"]: e["singular_name_short"] for e in bootstrap_data["element_types"]}
    
    # Recalibrate model against previous GW actuals
    state = recalibrate_model(state, headers, active_gw)
    state["last_updated_gw"] = target_gw
    weights = state["calibration_weights"]

    # Parse all players
    players = {}
    new_arrivals = []
    for raw_p in bootstrap_data.get("elements", []):
        p = normalize_player(raw_p, teams, element_types)
        players[p["id"]] = p
        if p.get("has_stale_pl_history") or p.get("minutes", 0) == 0:
            new_arrivals.append(f"- {p['name']} ({p['team']})")

    new_arrivals_str = "\n".join(new_arrivals) if new_arrivals else "None"
    market_str = "Market data initialized."

    # --- THE DATA ORACLE: HUMAN INTELLIGENCE OVERRIDES ---
    if XMINS_INPUT:
        print(f"Processing Human Oracle Input: {XMINS_INPUT}")
        for override in XMINS_INPUT.split(","):
            if ":" in override:
                name_part, min_part = override.split(":")
                name_part = name_part.strip().lower()
                try:
                    target_mins = float(min_part.strip())
                    for pid, p in players.items():
                        if name_part in p["name"].lower() or name_part in p.get("web_name", "").lower():
                            xmins_overrides[str(pid)] = target_mins
                            print(f"   -> ORACLE OVERRIDE: {p['name']} locked to {target_mins} mins.")
                except ValueError:
                    print(f"   -> WARNING: Could not parse override '{override}'")
    # -----------------------------------------------------
    
    current_squad_ids = []
    bank = 0.0
    total_liquid_budget = 100.0
    free_transfers = "Unlimited" if target_gw == 1 else 1
    required_bank_reservation = 0.0

    if target_gw > 1:
        try:
            team_resp = requests.get(f"https://fantasy.premierleague.com/api/entry/{FPL_TEAM_ID}/event/{target_gw-1}/picks/", headers=headers)
            if team_resp.status_code == 200:
                team_data = team_resp.json()
                current_squad_ids = [pick["element"] for pick in team_data.get("picks", [])]
                entry_history = team_data.get("entry_history", {})
                bank = entry_history.get("bank", 0) / 10.0
                total_liquid_budget = entry_history.get("value", 1000) / 10.0
        except Exception as e:
            print(f"WARNING: Could not fetch squad for team {FPL_TEAM_ID}: {e}")

    try:
        fixtures_resp = requests.get("https://fantasy.premierleague.com/api/fixtures/", headers=headers)
        if fixtures_resp.status_code == 200:
            fixtures_data = fixtures_resp.json()
        else:
            fixtures_data = []
    except Exception as e:
        fixtures_data = []
        
    team_fdr_sum = {t: 0 for t in teams.keys()}
    team_fdr_count = {t: 0 for t in teams.keys()}
    for f in fixtures_data:
        event = f.get("event")
        if event and target_gw <= event < target_gw + 4:
            team_a, team_h = f.get("team_a"), f.get("team_h")
            if team_a in team_fdr_sum:
                team_fdr_sum[team_a] += f.get("team_a_difficulty", 3)
                team_fdr_count[team_a] += 1
            if team_h in team_fdr_sum:
                team_fdr_sum[team_h] += f.get("team_h_difficulty", 3)
                team_fdr_count[team_h] += 1
                
    team_avg_fdr = {t: (team_fdr_sum[t] / team_fdr_count[t] if team_fdr_count[t] > 0 else 3.0) for t in teams.keys()}

    # 1. Build Dynamic Gameweek Matrix (FDR per GW)
    team_gw_fdr = {t_id: [6.0] * 4 for t_id in teams.keys()} # Default 6.0 = Blank GW
    for f in fixtures_data:
        event = f.get("event")
        if event and target_gw <= event < target_gw + 4:
            t = event - target_gw
            team_a, team_h = f.get("team_a"), f.get("team_h")
            if team_a in team_gw_fdr:
                team_gw_fdr[team_a][t] = f.get("team_a_difficulty", 3) if team_gw_fdr[team_a][t] == 6.0 else 1.0
            if team_h in team_gw_fdr:
                team_gw_fdr[team_h][t] = f.get("team_h_difficulty", 3) if team_gw_fdr[team_h][t] == 6.0 else 1.0

    # 2. Build EV Matrix for all players across horizons
    ev_matrix = {}
    valid_ids = list(players.keys())
    for pid in valid_ids:
        p = players[pid]
        ev_matrix[pid] = [0.0] * 4
        
        if p.get("status") not in ["a", "d"]:
            continue
            
        t_id = p["team_id"]
        ev_matrix[pid][0] = get_ensemble_ev(p, xmins_overrides, market_data, weights)
        
        base_ev = get_base_ev(p, xmins_overrides, weights)
        for t in range(1, 4):
            fdr = team_gw_fdr[t_id][t]
            if fdr == 6.0: 
                ev_matrix[pid][t] = 0.0
            else:
                fdr_multiplier = 1.0 + (3.0 - fdr) * 0.10
                ev_matrix[pid][t] = max(0.0, base_ev * fdr_multiplier)

    # 3. Execute Phase 1: True MPO Solver
    starter_candidates = [players[i] for i in valid_ids if players[i].get("cost", 0) >= 6.0][:11]
    bench_discount = 1.0 if ACTIVE_CHIP == "BENCH_BOOST" else calculate_dynamic_bench_discount(starter_candidates, xmins_overrides)

    optimal_squad, transfer_plan = solve_multi_period_model(
        players, 
        ev_matrix, 
        current_squad_ids, 
        total_liquid_budget - required_bank_reservation, 
        free_transfers, 
        bench_discount,
        horizons=4,
        risk_posture=RISK_POSTURE
    )

    # 4. Execute Phase 2: Micro-Optimization (Starting XI & Captaincy Selection for t=0)
    sub_prob = pulp.LpProblem("Phase2_StartingXI", pulp.LpMaximize)
    s_vars = pulp.LpVariable.dicts("s", [p["id"] for p in optimal_squad], cat="Binary")
    c_vars = pulp.LpVariable.dicts("c", [p["id"] for p in optimal_squad], cat="Binary")
    
    cap_mult = 2.0 if ACTIVE_CHIP == "TRIPLE_CAPTAIN" else 1.0
    
    sub_objective = []
    for p in optimal_squad:
        ev_1gw = ev_matrix[p["id"]][0]
        ownership = p.get("own", 0.0) / 100.0
        
        if RISK_POSTURE == "SHIELD":
            rank_threat_gravity = (ev_1gw * (ownership ** 2) * 1.50)
        elif RISK_POSTURE == "CHASE":
            rank_threat_gravity = -(ev_1gw * ownership * 0.50)
        else:
            rank_threat_gravity = (ev_1gw * (ownership ** 2) * 0.75)
            
        sub_objective.append( (ev_1gw * s_vars[p["id"]]) + ((ev_1gw * cap_mult + rank_threat_gravity) * c_vars[p["id"]]) )
        
    sub_prob += pulp.lpSum(sub_objective)
    sub_prob += pulp.lpSum([s_vars[p["id"]] for p in optimal_squad]) == 11
    sub_prob += pulp.lpSum([c_vars[p["id"]] for p in optimal_squad]) == 1
    
    for p in optimal_squad:
        sub_prob += c_vars[p["id"]] <= s_vars[p["id"]]
            
    sub_prob += pulp.lpSum([s_vars[p["id"]] for p in optimal_squad if p["pos_id"] == 1]) == 1
    sub_prob += pulp.lpSum([s_vars[p["id"]] for p in optimal_squad if p["pos_id"] == 2]) >= 3
    sub_prob += pulp.lpSum([s_vars[p["id"]] for p in optimal_squad if p["pos_id"] == 3]) >= 3
    sub_prob += pulp.lpSum([s_vars[p["id"]] for p in optimal_squad if p["pos_id"] == 4]) >= 1
    
    sub_prob.solve(pulp.PULP_CBC_CMD(msg=False))
    
    starters, bench = [], []
    cap = None
    for p in optimal_squad:
        if s_vars[p["id"]].varValue and s_vars[p["id"]].varValue > 0.5:
            starters.append(p)
            if c_vars[p["id"]].varValue and c_vars[p["id"]].varValue > 0.5:
                cap = p
        else:
            bench.append(p)
            
    starters.sort(key=lambda x: x["pos_id"])
    bench_gk = [p for p in bench if p["pos_id"] == 1]
    bench_outfield = sorted([p for p in bench if p["pos_id"] != 1], key=lambda x: ev_matrix[x["id"]][0], reverse=True)
    bench = bench_gk + bench_outfield
    
    starters_sorted_by_1gw = sorted(starters, key=lambda x: ev_matrix[x["id"]][0], reverse=True)
    vice = next((p for p in starters_sorted_by_1gw if not cap or p["id"] != cap["id"]), starters_sorted_by_1gw[0])
    
    optimal_squad = starters + bench

    european_flags = check_european_congestion_flags(starters, fixtures_data, target_gw)
    mitigation_flags_str = "\n".join(european_flags) if european_flags else "[No active mitigation warning flags triggered]"

    projected_starting_xP = sum(get_ensemble_ev(p, xmins_overrides, market_data, weights) for p in starters)
    if cap:
        cap_mult = 2.0 if ACTIVE_CHIP == "TRIPLE_CAPTAIN" else 1.0
        projected_starting_xP += get_ensemble_ev(cap, xmins_overrides, market_data, weights) * cap_mult
        
    state["pending_evaluation"] = {
        "gw": target_gw,
        "projected_xP": round(projected_starting_xP, 2),
        "captain": cap["name"] if cap else None
    }

    save_state(state)
    
    locked_squad_str = f"--- MATHEMATICALLY LOCKED SQUAD (Liquid Value: £{total_liquid_budget:.1f}m | Reserved Bank: £{required_bank_reservation:.1f}m) ---\n"
    locked_squad_str += f"ACTIVE CHIP STATUS: {ACTIVE_CHIP}\n"
    
    if current_squad_ids:
        optimal_ids = [p["id"] for p in optimal_squad]
        transfers_in = [p["name"] for p in optimal_squad if p["id"] not in current_squad_ids]
        transfers_out = [players[i]["name"] for i in current_squad_ids if i not in optimal_ids]
        locked_squad_str += f"TRANSFERS OUT: {', '.join(transfers_out) if transfers_out else 'None'}\n"
        locked_squad_str += f"TRANSFERS IN: {', '.join(transfers_in) if transfers_in else 'None'}\n\n"
        
    def count_pos(group, pos_id): return len([p for p in group if p["pos_id"] == pos_id])
    formation = f"{count_pos(starters, 2)}-{count_pos(starters, 3)}-{count_pos(starters, 4)}"
    
    locked_squad_str += f"STARTING XI (Formation: {formation}):\n"
    for p in starters:
        is_cap = " (C)" if cap and p["id"] == cap["id"] else ""
        is_vice = " (VC)" if vice and p["id"] == vice["id"] else ""
        pid_str = str(p["id"])
        xmins = float(xmins_overrides[pid_str]) if pid_str in xmins_overrides else estimate_xmins(p)
        actual_ev = round(get_base_ev(p, weights, xmins_overrides), 2)
        locked_squad_str += f"- {p['name']} ({p['team']}, {p['pos']}, £{p['cost']}m, Proj. Mins: {xmins:.1f}, TRUE 1-GW EV: {actual_ev}){is_cap}{is_vice}\n"
        
    locked_squad_str += "\nBENCH:\n"
    for i, p in enumerate(bench):
        pid_str = str(p["id"])
        xmins = float(xmins_overrides[pid_str]) if pid_str in xmins_overrides else estimate_xmins(p)
        actual_ev = round(get_base_ev(p, weights, xmins_overrides), 2)
        locked_squad_str += f"Slot {i+1}: {p['name']} ({p['team']}, {p['pos']}, £{p['cost']}m, Proj. Mins: {xmins:.1f}, TRUE 1-GW EV: {actual_ev})\n"
       
    locked_squad_str += f"\n### TACTICAL MITIGATION OPTION FLAGS\n{mitigation_flags_str}\n\n"
    
    if transfer_plan:
        locked_squad_str += "### MULTI-PERIOD TRANSFER TREE (MPO)\n"
        locked_squad_str += "\n".join(transfer_plan) + "\n\n"

    chip_recommendations = evaluate_chip_thresholds(starters, bench, ev_matrix, ACTIVE_CHIP)
    locked_squad_str += "### ALGORITHMIC CHIP RECOMMENDATIONS\n"
    for rec in chip_recommendations:
        locked_squad_str += f"• {rec}\n"

    macro_squad_4gw_xp = sum(get_macro_ev(p, team_avg_fdr, weights, xmins_overrides) for p in optimal_squad)
    
    from fpl_monte_carlo import run_monte_carlo_simulations
    mc_players = {p["id"]: {"est_xmins": estimate_xmins(p), "xgi_90": p["xgi_90"], "pos_id": p["pos_id"], "ep_next": p["ep_next"]} for p in starters}
    mc_results = run_monte_carlo_simulations(mc_players, num_trials=1000)
    
    starter_floor = sum(res["floor"] for res in mc_results.values())
    starter_ceiling = sum(res["ceiling"] for res in mc_results.values())

    locked_squad_str += "\n"
    locked_squad_str += "================================================================================\n"
    locked_squad_str += "SQUAD HEALTH & VARIANCE REPORT\n"
    locked_squad_str += "================================================================================\n"
    locked_squad_str += f"• 1-GW Expected Yield (Odds-Adjusted): {projected_starting_xP:.2f} pts\n"
    locked_squad_str += f"• 4-GW Structural Horizon xP (Squad):  {macro_squad_4gw_xp:.2f} pts\n"
    locked_squad_str += f"• Stochastic 10th Percentile Floor:    {starter_floor:.1f} pts\n"
    locked_squad_str += f"• Stochastic 90th Percentile Ceiling:  {starter_ceiling:.1f} pts\n"
    locked_squad_str += "================================================================================\n"

    return target_gw, bank, free_transfers, locked_squad_str, market_str, new_arrivals_str

def build_prompt(target_gw, bank, free_transfers, locked_squad_str, market_str, new_arrivals_str, live_news):
    gw1_override = ""
    if target_gw == 1 or str(free_transfers).lower() == "unlimited":
        gw1_override = "\n    6. PRE-SEASON RULE OVERRIDE: Gameweek 1 has UNLIMITED free transfers. Ignore point-hit constraints (Law 4)."

    if WORKFLOW_INPUT == "post_gameweek_review":
        action_type = "Post-Gameweek Strategic Review & Market Volatility Audit"
        phase_instructions = (
            "- FOCUS: Backward-looking performance evaluation and medium-term squad positioning.\n"
            "- Explain the Model Recalibration results and residual error from the previous Gameweek.\n"
            "- Evaluate price volatility, impending price rises/falls, and early transfer timing to protect team value.\n"
            "- Detail the MULTI-PERIOD TRANSFER TREE (MPO) roadmap for GW+1 through GW+3."
        )
    elif WORKFLOW_INPUT == "pre_gameweek_deadline":
        action_type = "Pre-Gameweek Final Deadline Lock & Late ITK Leak Audit"
        phase_instructions = (
            "- FOCUS: Forward-looking immediate execution for the upcoming deadline.\n"
            "- Focus heavily on verified press conference news, injury updates, and late lineup leaks.\n"
            "- Confirm any Human Oracle xMins overrides applied.\n"
            "- Lock in absolute final Starting XI, Captain (C), Vice-Captain (VC), and Bench Order."
        )
    else:
        action_type = "Full Weekly Execution & Analytical Breakdown"
        phase_instructions = (
            "- Provide a balanced breakdown covering transfer economics, market volatility, and upcoming fixture geometry."
        )

    focus_instructions = (
        f"1. 11-Man Verification Lock & Strict xMins Audit: Output the exact mathematically locked Starting XI and Bench provided. Do NOT change any player, captain, bench order, or team affiliation tag.\n"
        f"2. Phase-Specific Focus ({action_type}):\n{phase_instructions}\n"
        f"3. Visual Aesthetics: Include monospaced ASCII pitch maps in Section 1 and Section 4 using markdown text codeblocks. Format Section 2 strictly as single-line bullet points with bold player names. Avoid wide Markdown tables.\n"
        f"4. Analytical Justification: Use the EXACT 'TRUE 1-GW EV' numbers provided in the mathematically locked squad list below. Do NOT invent or hallucinate Expected Value (EV) numbers.\n"
        f"5. Transfer Trees & Chips: In Section 3, explicitly explain the MULTI-PERIOD TRANSFER TREE roadmap and the ALGORITHMIC CHIP RECOMMENDATIONS provided in the payload.\n"
        f"6. MANDATORY SIGN-OFF: Conclude your response with the boxed 'FINAL LOCKED-IN SQUAD SUMMARY' ASCII block."
    )

    prompt = f"""
    Run the {action_type} for Gameweek {target_gw}.
    
    ### CURRENT SQUAD STATE & ECONOMICS
    - Current Bank Balance: £{bank}m | Saved Free Transfers: {free_transfers}
    
{locked_squad_str}

    ### NEW ARRIVALS & FOREIGN TRANSFERS (ZERO PL HISTORY)
    The following players are new additions or foreign signings lacking Premier League historical baselines:
{new_arrivals_str}

    ### ACTIVE 2026/27 TRANSFER MARKET WATCHLIST
{market_str}
    
    {live_news}
    
    ### MANDATORY ANALYTICAL CONSTRAINTS
    1. Base all transfer and squad analysis STRICTLY on the Mathematically Locked Squad provided.
    2. Do NOT hallucinate players who are not currently active in the Premier League.
    3. Evaluate incoming transfer replacements STRICTLY using the ACTIVE 2026/27 TRANSFER MARKET WATCHLIST provided.
    4. LIVE NEWS OVERRIDE: Cross-reference the Market Watchlist against LIVE ITK NEWS and LONG TERM INJURIES. Ignore search items referencing non-Premier League players.
    5. FOREIGN TRANSFERS: Apply Law 7 to any players listed under NEW ARRIVALS. Highlight them for manual monitoring in Section 1.{gw1_override}
    
    ### DATA INSTRUCTIONS FOR EVALUATION
    {focus_instructions}
    
    Execute the full 5-section quantitative breakdown based strictly on your system instructions.
    """
    return prompt

def send_to_discord(webhook_url, text):
    chunks = []
    current_chunk = ""
    for line in text.split("\n"):
        while len(line) > 1800:
            if len(current_chunk) > 0:
                chunks.append(current_chunk)
                current_chunk = ""
            chunks.append(line[:1800])
            line = line[1800:]
            
        if len(current_chunk) + len(line) + 1 > 1800:
            chunks.append(current_chunk)
            current_chunk = line + "\n"
        else:
            current_chunk += line + "\n"
            
    if current_chunk.strip():
        chunks.append(current_chunk)
        
    for chunk in chunks:
        requests.post(webhook_url, json={"content": chunk})

def main():
    target_gw, bank, free_transfers, locked_squad_str, market_str, new_arrivals_str = get_fpl_data()
    print("--- FETCHING LIVE WEB SEARCH DATA ---")
    live_news = get_live_fpl_news()
    
    prompt = build_prompt(target_gw, bank, free_transfers, locked_squad_str, market_str, new_arrivals_str, live_news)
    
    print("--- DATA FETCHED ---")
    print(f"Target GW: {target_gw} | Bank: {bank} | Transfers: {free_transfers} | Chip: {ACTIVE_CHIP}")
    print("--- QUERYING GEMINI API ---")
    
    try:
        response = client.models.generate_content(
            model='gemini-3.6-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                temperature=0.2 
            )
        )
    except Exception as e:
        print(f"CRITICAL ERROR generating content with Gemini: {str(e)}")
        sys.exit(1)
        
    content = response.text if response and response.text else ""
    
    if not content:
        print("ERROR: Gemini returned an empty response string.")
        sys.exit(1)

    print(f"--- GEMINI RESPONSE RECEIVED ({len(content)} characters) ---")
    send_to_discord(DISCORD_WEBHOOK_URL, content)
    print("--- DISCORD DELIVERY COMPLETE ---")

if __name__ == "__main__":
    main()
