"""
fpl_compare_players.py — Head-to-Head Player Audit Tool (Multi-Period Matrix Aligned)

Executes side-by-side player comparisons across 1-GW EV, 8-GW Deep-Tree Horizon xP, 
week-by-week EV/xMins matrices, and stochastic risk bounds from ml_projections.json.
"""

import os
import sys
import json
import requests
import unicodedata

from fpl_funcs import (
    estimate_xmins, normalize_player, get_gameweek_state, get_live_price_deltas
)

DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")
PLAYER_COMPARE_INPUT = os.environ.get("PLAYER_COMPARE", "")

if "," in PLAYER_COMPARE_INPUT:
    parts = PLAYER_COMPARE_INPUT.split(",")
    PLAYER_A_INPUT = parts[0].strip()
    PLAYER_B_INPUT = parts[1].strip()
else:
    PLAYER_A_INPUT = os.environ.get("PLAYER_A", "").strip()
    PLAYER_B_INPUT = os.environ.get("PLAYER_B", "").strip()

RISK_POSTURE = os.environ.get("RISK_POSTURE", "NEUTRAL").upper()
STATE_FILE_PATH = "fpl_state.json"

if not DISCORD_WEBHOOK_URL or not PLAYER_A_INPUT or not PLAYER_B_INPUT:
    print("CRITICAL ERROR: Missing DISCORD_WEBHOOK_URL secret or player inputs.")
    sys.exit(1)

def normalize_text(text: str) -> str:
    """Strips accents and normalizes special characters (Ø, Æ, ð, etc.)."""
    if not text: return ""
    nfkd_form = unicodedata.normalize('NFD', text)
    clean_text = ''.join([c for c in nfkd_form if not unicodedata.combining(c)])
    char_map = {'ø': 'o', 'Ø': 'O', 'æ': 'ae', 'Æ': 'AE', 'ð': 'd', 'Ð': 'D', 'ß': 'ss'}
    for char, repl in char_map.items(): clean_text = clean_text.replace(char, repl)
    return clean_text.lower().strip()

COMMON_ALIASES = {
    "kdb": "de bruyne", 
    "vvd": "van dijk", 
    "trent": "alexander-arnold", 
    "taa": "alexander-arnold", 
    "bruno": "fernandes"
}

def resolve_player(search_term: str, players: dict, ml_proj_data: dict):
    """Resolves player search term using exact, alias, or substring matching against projections & FPL data."""
    norm_term = normalize_text(search_term)
    if norm_term in COMMON_ALIASES: norm_term = COMMON_ALIASES[norm_term]

    # Search by ID / Name mapping
    for pid, p in players.items():
        pid_str = str(pid)
        ml_name = ml_proj_data.get(pid_str, {}).get("name", "")
        if norm_term in [normalize_text(p["name"]), normalize_text(p.get("full_name", "")), normalize_text(ml_name)]:
            return p, pid_str, None

    candidates = []
    for pid, p in players.items():
        pid_str = str(pid)
        ml_name = ml_proj_data.get(pid_str, {}).get("name", "")
        if norm_term in normalize_text(p["name"]) or norm_term in normalize_text(p.get("full_name", "")) or norm_term in normalize_text(ml_name):
            candidates.append((p, pid_str))

    if len(candidates) == 1:
        return candidates[0][0], candidates[0][1], None
    elif len(candidates) > 1:
        exact_web = [c for c in candidates if normalize_text(c[0]["name"]) == norm_term]
        if len(exact_web) == 1: return exact_web[0][0], exact_web[0][1], None
        cand_list = ", ".join([f"**{c[0]['name']}** ({c[0]['team']})" for c in candidates[:5]])
        return None, None, f"Multiple players matched '{search_term}': {cand_list}."

    return None, None, f"Could not resolve player '{search_term}'."

def fetch_data_and_compare():
    headers = {"User-Agent": "FPL-Comparison-Tool/5.0"}
    try:
        resp = requests.get("https://fantasy.premierleague.com/api/bootstrap-static/", headers=headers)
        if resp.status_code != 200: sys.exit(1)
        bootstrap_data = resp.json()
    except Exception as e:
        print(f"CRITICAL ERROR: {e}"); sys.exit(1)

    active_gw, target_gw = get_gameweek_state(bootstrap_data)
    teams = {t["id"]: t["short_name"] for t in bootstrap_data["teams"]}
    element_types = {e["id"]: e["singular_name_short"] for e in bootstrap_data["element_types"]}

    players = {raw_p["id"]: normalize_player(raw_p, teams, element_types) for raw_p in bootstrap_data.get("elements", [])}

    price_deltas = get_live_price_deltas(players)
    for pid, p in players.items():
        p["price_delta_prob"] = price_deltas.get(pid, 0.0)

    # Load ML Projections generated by train_models.py
    ml_proj_data = {}
    if os.path.exists("ml_projections.json"):
        try:
            with open("ml_projections.json", "r") as f:
                ml_proj_data = json.load(f)
        except Exception as e:
            print(f"WARNING: Could not load ml_projections.json: {e}")

    p1, pid1_str, err1 = resolve_player(PLAYER_A_INPUT, players, ml_proj_data)
    p2, pid2_str, err2 = resolve_player(PLAYER_B_INPUT, players, ml_proj_data)

    if err1 or err2:
        err_msg = f"### ⚠️ PLAYER RESOLUTION FAILURE\n• {err1 or ''}\n• {err2 or ''}"
        requests.post(DISCORD_WEBHOOK_URL, json={"content": err_msg})
        sys.exit(1)

    # Extract metrics for Player 1
    p1_proj = ml_proj_data.get(pid1_str, {})
    ev_1gw_1 = float(p1_proj.get("ml_ev_1gw", p1.get("ep_next", 0.0)))
    macro_8gw_1 = float(p1_proj.get("ml_ev_8gw", ev_1gw_1 * 8))
    xmins1 = float(p1_proj.get("ml_xmins", estimate_xmins(p1)))
    floor1 = float(p1_proj.get("mc_floor_ev", ev_1gw_1 * 0.7))
    ceil1 = float(p1_proj.get("mc_ceiling_ev", ev_1gw_1 * 1.3))
    ev_matrix_1 = p1_proj.get("ml_ev_matrix", [ev_1gw_1] * 8)
    xmins_matrix_1 = p1_proj.get("ml_xmins_matrix", [xmins1] * 8)
    val_1gw_1 = ev_1gw_1 / p1["cost"] if p1["cost"] > 0 else 0.0
    val_8gw_1 = macro_8gw_1 / p1["cost"] if p1["cost"] > 0 else 0.0

    # Extract metrics for Player 2
    p2_proj = ml_proj_data.get(pid2_str, {})
    ev_1gw_2 = float(p2_proj.get("ml_ev_1gw", p2.get("ep_next", 0.0)))
    macro_8gw_2 = float(p2_proj.get("ml_ev_8gw", ev_1gw_2 * 8))
    xmins2 = float(p2_proj.get("ml_xmins", estimate_xmins(p2)))
    floor2 = float(p2_proj.get("mc_floor_ev", ev_1gw_2 * 0.7))
    ceil2 = float(p2_proj.get("mc_ceiling_ev", ev_1gw_2 * 1.3))
    ev_matrix_2 = p2_proj.get("ml_ev_matrix", [ev_1gw_2] * 8)
    xmins_matrix_2 = p2_proj.get("ml_xmins_matrix", [xmins2] * 8)
    val_1gw_2 = ev_1gw_2 / p2["cost"] if p2["cost"] > 0 else 0.0
    val_8gw_2 = macro_8gw_2 / p2["cost"] if p2["cost"] > 0 else 0.0

    diff_1gw = abs(ev_1gw_1 - ev_1gw_2)
    diff_8gw = abs(macro_8gw_1 - macro_8gw_2)
    winner = p1['name'] if macro_8gw_1 > macro_8gw_2 else (p2['name'] if macro_8gw_2 > macro_8gw_1 else "Equal")
    rec = f"**{winner}** projects higher 8-GW structural value (+{diff_1gw:.2f} 1-GW EV | +{diff_8gw:.2f} 8-GW xP)."
    if p1["pos"] != p2["pos"]: 
        rec += f" [Cross-Position Audit: {p1['pos']} vs. {p2['pos']}]"

    def price_trend_str(prob):
        if prob > 0.0: return "Rising (+£0.1m)"
        if prob < 0.0: return "Falling (-£0.1m)"
        return "Stable (£0.0m)"

    p1_str = f"{p1['name']} ({p1['team']})"
    p2_str = f"{p2['name']} ({p2['team']})"

    def fmt_row(lbl, v1, v2):
        return f" {lbl:<24} | {str(v1):<25} | {str(v2):<25}\n"

    def fmt_matrix(mat):
        return "[" + ", ".join([f"{x:.1f}" for x in mat[:8]]) + "]"

    ascii_table = "```yaml\n"
    ascii_table += "================================================================================\n"
    ascii_table += f" HEAD-TO-HEAD QUANTITATIVE PLAYER AUDIT (GW {target_gw})\n"
    ascii_table += "================================================================================\n"
    ascii_table += fmt_row("METRIC", p1_str, p2_str)
    ascii_table += "--------------------------------------------------------------------------------\n"
    ascii_table += fmt_row("Position", p1["pos"], p2["pos"])
    ascii_table += fmt_row("Cost", f"£{p1['cost']:.1f}m", f"£{p2['cost']:.1f}m")
    ascii_table += fmt_row("Ownership", f"{p1['own']:.1f}%", f"{p2['own']:.1f}%")
    ascii_table += fmt_row("Top 10k EO", f"{p1_proj.get('top_10k_eo', p1['own']):.1f}%", f"{p2_proj.get('top_10k_eo', p2['own']):.1f}%")
    ascii_table += fmt_row("Price Delta Trend", price_trend_str(p1["price_delta_prob"]), price_trend_str(p2["price_delta_prob"]))
    ascii_table += fmt_row("Baseline xMins", f"{xmins1:.1f}", f"{xmins2:.1f}")
    ascii_table += fmt_row("Adjusted xGI / 90", f"{p1['xgi_90']:.2f}", f"{p2['xgi_90']:.2f}")
    ascii_table += "--------------------------------------------------------------------------------\n"
    ascii_table += fmt_row("1-GW Expected Yield", f"{ev_1gw_1:.2f} pts", f"{ev_1gw_2:.2f} pts")
    ascii_table += fmt_row("8-GW Horizon xP", f"{macro_8gw_1:.2f} pts", f"{macro_8gw_2:.2f} pts")
    ascii_table += fmt_row("Stochastic Floor/Ceil", f"{floor1:.1f} / {ceil1:.1f}", f"{floor2:.1f} / {ceil2:.1f}")
    ascii_table += fmt_row("1-GW Value (EV / £m)", f"{val_1gw_1:.2f} pts/£m", f"{val_1gw_2:.2f} pts/£m")
    ascii_table += fmt_row("8-GW Value (xP / £m)", f"{val_8gw_1:.2f} pts/£m", f"{val_8gw_2:.2f} pts/£m")
    ascii_table += "--------------------------------------------------------------------------------\n"
    ascii_table += fmt_row("8-GW EV Matrix", fmt_matrix(ev_matrix_1), fmt_matrix(ev_matrix_2))
    ascii_table += fmt_row("8-GW xMins Matrix", fmt_matrix(xmins_matrix_1), fmt_matrix(xmins_matrix_2))
    ascii_table += "================================================================================\n"
    ascii_table += f" Risk Posture: {RISK_POSTURE}\n"
    ascii_table += f" Algorithmic Recommendation: {rec}\n"
    ascii_table += "================================================================================\n"
    ascii_table += "```"

    requests.post(DISCORD_WEBHOOK_URL, json={"content": ascii_table})
    print("Head-to-head audit delivered successfully to Discord.")

if __name__ == "__main__":
    fetch_data_and_compare()